### PR TITLE
Various updates to witness plugin

### PR DESCRIPTION
**Pull request by colltoaction**
These changes remove deprecated Gradle features that make the plugin incompatible with Gradle >= 5.0.

With this, we **upgrade to Gradle 5.4.1**.

We add **functional tests** using Gradle's TestKit (run with ./gradlew test).

We add "check all deps" behavior as seen in #2, with an `exclude` list for snapshot dependencies.

We also take this chance to move from **Groovy to Kotlin**:

1. we first migrate the build script (`build.gradle` -> `build.gradle.kts`)
1. then, we migrate the plugin implementation (`WitnessPlugin.groovy` -> `WitnessPlugin.kt`)

We also remove the reproducibility custom tasks in favor of Debian's `strip-nondeterminism` tool. Here are the reproducible build steps: https://github.com/rsksmart/reproducible-builds/pull/12.

### CODE REVIEW

**Review by diega — DISMISSED** [review]

**Comment by bernacodesido** [comment]
Why should we migrate the implementation?

**Comment by colltoaction** [comment]
We have more experience with Kotlin than Groovy in the company. Kotlin also brings benefits such as type-safety and better IDE integration.

https://blog.gradle.org/kotlin-meets-gradle
https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/
https://dev.to/jmfayard/how-kotlin-makes-editing-your-gradle-build-less-frustrating-232l

**Review by lsebrie — DISMISSED** [review]
LGTM

**Comment by bernacodesido** [comment]
I agree the gradle upgrade and removing the reproducible gradle task. Not changing a language just because you like it and want to.
Gradle already uses groovy, so your are just adding another language and complexity, not solving any problem.

This a security plugin and changes has not to be taken lightly.

**Comment by colltoaction** [comment]
The issue you mention about complexity doesn't sound right. [Gradle](https://github.com/gradle/gradle) is written in loads of different languages:

image

Maybe these changes can be audited so we can move forward?

**Comment by joaquinlpereyra-iov** [comment]
Hi everyone,

I'll be reviewing this changes to make sure we have not introduce any unintended change on the move from Groovy to Kotlin. This should be fairly quick so you can move on with other, more interesting tasks :) 

I'll also be reviewing more generally our whole implementation of reproducible builds to make sure we are correctly checking our dependencies. I'm sure I'll need your help @collheesi & co, so I'll probably be approaching you guys one of these days so I'm positive I understand our current strategy. 

Also, and for future reference, I think it would be better for everyone if  changes on critical security components like these are discussed with security **before** work on them is started. This is so we can all agree on an optimal strategy to move forward the codebase and no one wastes times working on a feature which may be problematic :).

I'll get to it!

**Comment by joaquinlpereyra-iov** [comment]
LGTM :). Kotlin code effectively does the same as the previous Groovy code.

**Review by bernacodesido — CHANGES_REQUESTED** [review]
Could you add tests to be sure that the new code has the same behavior than the old one and nothing is broken?

**Review by bernacodesido — DISMISSED** [review]
Also, I was testing the plugin and when I run `./gradlew --no-daemon assemble` fails with:

```
Verification of Gradle distribution failed!

Your Gradle distribution may have been tampered with.
Confirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.

 Distribution Url: https://services.gradle.org/distributions/gradle-5.4.1-all.zip
Download Location: /Users/username/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1-all.zip
Expected checksum: '14cd15fc8cc8705bd69dcfa3c8fefb27eb7027f5de4b47a8b279218f76895a92'
  Actual checksum: '14cd15fc8cc8705bd69dcfa3c8fefb27eb7027f5de4b47a8b279218f76895a91'
```

And if I download manually the wrapper and get the SHA256:

```
$ wget https://services.gradle.org/distributions/gradle-5.4.1-all.zip
$ shasum -a 256 ~/Downloads/gradle-5.4.1-all.zip 
14cd15fc8cc8705bd69dcfa3c8fefb27eb7027f5de4b47a8b279218f76895a91  /Users/username/Downloads/gradle-5.4.1-all.zip
```

**Comment by colltoaction** [comment]
Thanks, my fault!

**Comment by colltoaction** [comment]
As requested:

1. I added functional tests using Gradle's TestKit (run with `./gradlew test`)
2. I implemented #2, with an `exclude` list for snapshot dependencies

CC @bcodesido @joaquinlpereyra-iov

**Pull request closed without merging**
